### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DR-3araby** [piccoripico/Text-Formatting-and-Editing-in-the-Context-Menu#1]
After downloading this addon it shows me this error
------------------------------------------------------------------------------
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-04-11 03:02:05

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 372, in contextMenuEvent
  File "_aqt.hooks", line 5278, in __call__
  File "C:\Users\Ahmed Elaraby\AppData\Roaming\Anki2\addons21\2143302836\__init__.py", line 377, in on_reviewer_context_menu
    web_instance = reviewer.web
AttributeError: 'QSplitter' object has no attribute 'web'

**Comment by piccoripico** [comment]
Sorry for the inconvenience. I've uploaded a modified one on AnkiWeb. Could you please update the addon (Anki -> Tools -> Add-ons -> Check for Updates) and share me what happened?

**Comment by piccoripico** [comment]
Closing this issue. Thank you for your contribution.
